### ISSUE TITLE
Manually Activating a Tile Doesnt Auto Attack Tokens within the Tile

### ISSUE THREAD

**Issue by Tyreal74** [ironmonk88/monks-active-tiles#117]
I set up a Manually Triggered tile requesting a Dex Saving Throw on the token within the tile area and continue if any failed. 

When the failure happens, I use an Attack Action on the token within the tile. This attack is linked to a trap actor with a trap attack.

The save is requested, but the trap doesnt then target the token to roll the damage (see attached Gif for Dex failing but no damage prompt. (anim doesnt reflect the attack - was just testing a ranged seqeunce)

Latest version of MATT, Foundry 9.249
![ligthning_trap](https://user-images.githubusercontent.com/20683739/153562596-6d7a2e99-1cff-4576-ab0a-ff0eaf8b8e0d.gif)
.

**Comment by ironmonk88** [comment]
The Attack action doesn't target tokens and roll attacks.
Because it's specific to each system how an attack works, I'd have to write custom code for each system, and although it's on the list, it's a lot of work to create an maintain, and is currently low priority.
So at the moment, you should get the chat card for the attack, which lets the system handle the attack.

**Comment by ironmonk88** [comment]
Closing this as I did my best to get the Attack action to include damage.
