### ISSUE TITLE
ideas to improve the system and possible BUGs

### ISSUE THREAD

**Issue by sethmod** [ironmonk88/monks-active-tiles#149]
Alter = put a duration time value of the attribute and make it have the possibility
to be permanent, last a few turns, a few rounds, or for some time timed or administered by the GM

Create Journal = I didn't quite understand how it works, I thought that when I entered Trigger it would create
a Journal document that I have already created and selected in a place on the map, but that didn't happen.
However, on the console I didn't see any errors being detected, what appeared was:

monks-active-tiles | Tile is triggering TokenDocumentPF2e {initialized: true, apps: {…}, _sheet: null, _object: TokenPF2e, _destroyed: false, …}

Pan Canvas = putting a timer would help a lot, this could make the GM hold the camera in one place for 3 seconds or so or so,
it would help a lot with more distracted players, because the movement is in very little time.

Reset Fog of War = it would be very interesting if you had the option to reset only for a specific player who gave Trigger, representing that he lost
the memory because affected by a labyrinth spell that made him forget the way, or something like that, I don't know if it's possible to do it, but it really would be
interesting.

Change Show Dialog = There is a button called On Yes Goto and another called On No Goto, I figured it would be a message that would appear
whether you pressed yes or no, which is actually a great idea, but when I pressed yes or no, no message appeared. I don't know if it was a problem
of the option or if it didn't do this function, anyway, it would be really cool if there could be a smart integration of this option, as if you
clicking on Yes, you can activate another effect on actions or another Tile, I don't know if it's possible, it would be interesting if it were possible with a single
Tile, I really liked this option, I wish it was working, but it is less important than Active Effects and Attack.

Trigger Tile = Honestly, I don't know what it does, I tried to use it but it crashed my PC every time I activated it, in this case, it crashed the foundry and the browser.

**Comment by ironmonk88** [comment]
* Alter - I think this is outside the realm of Active Tiles.  This would probably need another module to manage all of that.  If there is a module that adds that kind of functionality and has an API that Active Tiles could hook into, I think that would be doable.
* Create Journal - This is working for me, did you check the Notes layer to see if the Note was created?
* Pan Canvas - Preventing something from happening is a really good way to get bug reports.  Trust me, I accidentally added something like this with another function and it did not go well.  If players want to move the canvas they should be free to do so.  I also think with v10's improvements to pings this becomes a bit of a moot point.
* Reset Fog of War - I'd love to... but Foundry doesn't exactly support it.  I'll look into it again, but it would require me to recreate code to reset the fog of war and it just hasn't been a priority.
* Show Dialog - The Goto's will go to anchors, not just display messages.  That way you can do whatever you'd like on a yes or no.
* Trigger Tile - Literally triggers a Tile.  If you triggered the current tile, which is the default, without providing a way for the loop to stop. then it will most definitely crash your browser because it will get into an infinite loop of triggering itself.
