### ISSUE TITLE
Bug: Teleport tokens within Tile is broken

### ISSUE THREAD

**Issue by WeirdBread** [ironmonk88/monks-active-tiles#166]
Tile with option to teleport every token withing tile is broken. It worked on 1.0.64 version, but on 1.0.69 it doesn't. 

Error message: tile is not defined

![изображение](https://user-images.githubusercontent.com/79375204/163247544-0b4d01e2-f023-46f7-a6ea-a8eb6c2fdae3.png)

![изображение](https://user-images.githubusercontent.com/79375204/163247663-94e5e40a-c5e7-42c6-9ae1-b16eefc42218.png)

**Comment by Snugug** [comment]
I'm getting the same error trying to use `Tokens within tile` for request roll; as it's the same error and the same "select entity", I believe the errors are related. I'm also on 1.0.69, Forge v9, Build 268

**Comment by Snugug** [comment]
I think I've narrowed this down a bit using Find the Culprit!, but I can't narrow it down further because my display canvas stops being able to load and I can't test any further. Here are the potential conflicts:

* Enhanced Terrain Layer - 1.0.39
* Forien's Quest Log - 0.7.9
* FXMaster - 2.4.0
* Health Estimate - 27.00
* Initiative Double Click - 1.5
* Less Fog - 0.9.1
* Levels - 2.7.2
* Changelogs & Conflicts - 0.7.7
* libWrapper - 1.12.4.0
* The Mad Cartographer | Classic Dungeons 2 | Battlemap Pack - 1.14

Hope this helps you debug!

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
