### ISSUE TITLE
GURPS Support

### ISSUE THREAD

**Issue by Volksters** [ironmonk88/monks-active-tiles#179]
At the moment, there are a few things that GURPS doesn't work well with Active Tiles.

Add Items = Items do not get added onto inventory.
Alter (Attributes) = It works in some capacity but quite rudimentary for anything stats related.
Attack = Selecting Tokens but the Attack doesn't show up (GURPS uses a different method of handling attack so it's understandable here)
Hurt/Heal = Doesn't do anything so far.

Filters such as Find Item or Attributes are not working for the moment.

Request Rolls are a totally separate module more or less but it's related if the user/GM wants to see if the roll succeeds or not. 

I'll add up some more if I can find more issues with them. Thank you so much for your help, Monk!

**Comment by ironmonk88** [comment]
So there's not a lot I can do about this.
GURPS just... does things so differently that I'd find it really hard to make the changes.
I updated some things but I can't cover them all.  Unfortunately.

**Comment by ironmonk88** [comment]
So I worked on adding items, but I'm not sure how GURPS is doing it.  All other systems so far will add an item by just creating the document with the actor as the parent.  But even though GURPS will do that, it's not the list of items it will display on the character sheet.  Alter mostly seems to work.  Attack is working as expected.  Active Tiles doesn't actually automate an attack because every system does it differently and it's a lot of code to write for each one.  So at most, MATT just lets the GM know that an attack is requested.  Hurt/Heal isn't working because GURPS saves a max value for HP, but I can't find a way to edit it.  So it stays at zero, and Hurt/Heal won't go above the max.  So at some point the system needs to be able to change the max from being 0.  I didn't look into the filters.  And the Request Rolls are Tokenbar, and that's a whole other project to try and get it to work with that module.

**Comment by ironmonk88** [comment]
Closing this as I think most of the points has been taken care of.  At least the ones that I could address.
If there are any further specific issues please open an individual ticket for each point.
