### ISSUE TITLE
Active Tiles and Libruler Conflict

### ISSUE THREAD

**Issue by Armandeus66** [ironmonk88/monks-active-tiles#18]
Foundry gives an error stating there is a conflict between Active Tiles and Libruler.
I searched the console but couldn't find any more information.
Active Tiles version 1.0.17, Libruler version 0.0.9, Foundry 0.8.8

**Comment by ironmonk88** [comment]
This might be fixed on the release I'm working on, as I'm not able to replicate.
I'll flagged it to be checked again once the new version is out.

**Comment by ironmonk88** [comment]
New release is out, is this still an issue?

**Comment by Armandeus66** [comment]
I updated today, and yes, it is.

**Comment by ironmonk88** [comment]
It was only activating when the DragRuler module was inactive.
We're both trying to override the same function.  Active Tiles needs it to stop tokens, and libRuler needed it to generalize animations.
I was able to streamline the code a bit better and worked with libRuler to integrate the changes I needed into their code.  So in the absence of libRuler Active Tiles takes over, and when it's there, I can have libRuler do the work.

I also opened a ticket with Foundry to fix the issue I was having so that I didn't need to override in the first place.
