### ISSUE TITLE
Bug: Create Token (From MEJ Encounter)

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#185]
![image](https://user-images.githubusercontent.com/99844555/168164480-a8cf7615-b719-4620-8efa-f6106f31580a.png)

With "Avoid Others Token" on, this action fails to work.

monks-active-tiles |  ReferenceError: dest is not defined
    fn monks-active-tiles.js:821
    runActions monks-active-tiles.js:6633
    trigger monks-active-tiles.js:6588
    checkClick monks-active-tiles.js:6357
    checkClick monks-active-tiles.js:6252
    canvasClick monks-active-tiles.js:5571
    _onLeftClick2 monks-active-tiles.js:5551
    call_wrapper libWrapper-wrapper.js:620
    _onClickLeft2#0 libWrapper-wrapper.js:189
    callback foundry.js:24252
    _handleClickLeft2 foundry.js:24456
    _handleMouseDown foundry.js:24418
    emit index.js:202
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8
monks-active-tiles.js:13:13
    error monks-active-tiles.js:13
    runActions monks-active-tiles.js:6691
    trigger monks-active-tiles.js:6588
    checkClick monks-active-tiles.js:6357
    checkClick monks-active-tiles.js:6252
    canvasClick monks-active-tiles.js:5571
    _onLeftClick2 monks-active-tiles.js:5551
    call_wrapper libWrapper-wrapper.js:620
    _onClickLeft2#0 libWrapper-wrapper.js:189
    callback foundry.js:24252
    _handleClickLeft2 foundry.js:24456
    _handleMouseDown foundry.js:24418
    emit index.js:202
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8

**Comment by That-Italian-Guy** [comment]
Additional (related) error: the same happens if you try to "Avoid other tokens" when spawning tokens that are not part of a Monk's Journal Encounter.
![image](https://user-images.githubusercontent.com/106380880/170683323-e0f01b4d-bc28-4566-8276-24394ca39b07.png)

monks-active-tiles.js:13 monks-active-tiles |  ReferenceError: dest is not defined
    at TileDocument.fn (monks-active-tiles.js:821)
    at async TileDocument.runActions (monks-active-tiles.js:6633)
    at async TileDocument.trigger (monks-active-tiles.js:6588)
error @ monks-active-tiles.js:13
TileDocument.runActions @ monks-active-tiles.js:6691
async function (async)
TileDocument.runActions @ monks-active-tiles.js:6630
TileDocument.trigger @ monks-active-tiles.js:6588
TileDocument.checkClick @ monks-active-tiles.js:6357
checkClick @ monks-active-tiles.js:6252
canvasClick @ monks-active-tiles.js:5571
_onLeftClick @ monks-active-tiles.js:5539
🎁call_wrapper @ libWrapper-wrapper.js:619
🎁Canvas.prototype._onClickLeft#0 @ libWrapper-wrapper.js:188
callback @ foundry.js:24060
_handleClickLeft @ foundry.js:24247
_handleMouseDown @ foundry.js:24227
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.js:8
r.processPointerDown @ interaction.min.js:8
t.recursiveFindHit @ interaction.min.js:8
t.findHit @ interaction.min.js:8
r.processInteractive @ interaction.min.js:8
r.onPointerDown @ interaction.min.js:8

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
