### ISSUE TITLE
Bug: Attribute Filter followed by logic malfunction

### ISSUE THREAD

**Issue by matta725** [ironmonk88/monks-active-tiles#187]
Using filter by attribute using current tokens followed by checking entity count of current tokens causes token to stop moving. 

In this example shown below, it is meant for a 5e passive perception "detect trap" tile. When a token moves into the tile and they have a passive perception >= 15, they should stop and mention the trap. If not, they should continue moving as normal. 

What is happening is when they do not meet the passive perception check, the token stops moving. Not sure if this is worth mentioning, but when this happens my cursor has the spinning loading symbol (I am on Windows 10). 

![image](https://user-images.githubusercontent.com/86897172/168689294-8e17cd05-1834-4c0c-b37d-9fd71f7d5149.png)

**Comment by ironmonk88** [comment]
Not a bug.  It's just how Active Tiles has to work.
It needs to stop the token before it knows if it needs to stop the token.  Because if it doesn't stop the token, by the time it gets to that code it would be too late and the token would have to move back to where it should have stopped.

In instances like this, you'll have to find tokens with a passive perception < 15 and direct them to a 'Move' action, using the original destination as the location.

**Comment by matta725** [comment]
Very interesting! That fixes what I was dealing with for sure. Thank you so much for the fix!
