### ISSUE TITLE
BUG: Change Scene no longer working for non-GM

### ISSUE THREAD

**Issue by jocolamarco** [ironmonk88/monks-active-tiles#188]
I recently updated the module and the tiles with behaviour to change Scene are no longer working for my players. Only for the GM.
Previously this worked without any issues.

When the users click, nothing happens. there is also no error message in the console log.
Set-up examples below:
![image](https://user-images.githubusercontent.com/45291719/168783347-15c033c0-ebf7-49fd-b47a-9b04729f0a50.png)

Versions:
![image](https://user-images.githubusercontent.com/45291719/168783213-f616d949-bf5e-44fc-83ac-3962037d26bf.png)

**Comment by ironmonk88** [comment]
It's working for me.
Check to see if there's any other module interference by using Find the Culprit.
And is the game unpaused?  Tiles won't work for players unless the game is active.
If that's a requirement, then you can turn it off in the settings.

**Comment by jocolamarco** [comment]
Thanks, it seems that option was active.
Either it's new or it changed with the update?

Anyway, marking this one as closed :)

**Comment by ironmonk88** [comment]
It's a new change.
Players were activating things they shouldn't be able to, because the requests get sent to the GM... who can do things while the game is paused.
So it's a bit heavy handed, but I felt it was better to air on the side of caution than leave it open to players doing things they shouldn't be able to.  And the setting is there in case you have things like a Scene Menu that the players need access to.
