### ISSUE TITLE
[Feature Request] Token Rotation value for the Alter Action

### ISSUE THREAD

**Issue by That-Italian-Guy** [ironmonk88/monks-active-tiles#205]
Followup from request #201 - it doesn't look like it's curretly possible to access the _token.data.rotation_ value for Tokens using the Alter action. While token facing is usually not super important, it's quite useful when handling prefabs (whose rotation depend on the token they are attached to). At the moment the only alternative is to create a separate prefab with the desired rotation value, which can lead to quite some bloat.
![image](https://user-images.githubusercontent.com/106380880/171607863-4f18e915-0872-44bd-a9ef-d6e0e752ebcd.png)

Case use:
- set prefabs to spawn with the correct facing when using the Create Token Action.

**Comment by ironmonk88** [comment]
Just type in `rotation` that list is set by the system and depending on the system, some values may have been removed.  There's not much I can do about that since not using the system generated list will crash Foundry.

If you have Discord, there's a pretty amazing community on my server that can answer most of these questions.  [https://discord.gg/sFKeTe45](https://discord.gg/sFKeTe45)
