### ISSUE TITLE
Feature request : run on macro while tiles scene is active 

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/monks-active-tiles#214]
**[feature request] **
trigger tile based on specific macros being run on a while tile scene is active

**Comment by ironmonk88** [comment]
I mean... I'd just edit the original macro to include triggering the Tile.
You can check to see if the Tile exists first, but manually triggering it is pretty easy.
And if you don't want to edit the original Macro, you could always use a wrapper Macro, that called the original Macro, and then checked to see if the Tile was there for triggering.
That's probably way easier than triggering when the Macro triggers.  Especially since the code to trigger the other code would get hidden.  So you'd trigger the Macro and wonder why other things were happening.

**Comment by ironmonk88** [comment]
Closing this as I think there's a better workaround.
