### ISSUE TITLE
[Feature Request] Ignore transparency on movement, instead of just on click.

### ISSUE THREAD

**Issue by Janner3D** [ironmonk88/monks-active-tiles#231]
I noticed there was an option to ignore transparency on click. It would be incredibly useful if that option was available for movement, too, such as entering a circular platform.

**Comment by Mecheye** [comment]
+1 for this

This will go a long way towards helping produce the appropriate footfall noise for certain types of terrain. Right now that isn't possible because, for example, walking upon a metal hatch at the center of an O-shaped wooden floor will only produce the wooden floor footfall since the transparent center of the O will still count as the wooden floor for purposes of the Movement trigger. In order to properly have walking on the metal hatch produce the metal floor footfall the wooden floor would have to be split into four separate tiles so that the metal hatch is no longer covered.

This is one usage example that I found would benefit from this FR.

**Comment by ironmonk88** [comment]
This is mostly doable now.  You'd just need to split the "O" into two circles as the process for finding the border, doesn't find the "inside" border.
