### ISSUE TITLE
[BUG] Stop Sounds

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#403]
Stop Sounds fails to stop ambient sounds. No errors. 

(Going to be honest, I can't remember how this one was actually supposed to work. Is it meant to deactivate all ambient sounds on the scene? If so, the ambient sounds are staying activated.)

MATT 10.10
Foundry 10.291

**Comment by ironmonk88** [comment]
It's supposed to mute all Playlists.
Which is does.
It's just in a weird location, and probably shouldn't be there any more.
That action was created before the playlist action so it ended up doing double-duty in the beginning.

I've changed it so that the playlist action will take over, and added a feature to select the currently playing tracks.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
