### ISSUE TITLE
[BUG] Editing an Action Freezes Firefox

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#405]
Editing an action can rarely result in Firefox freezing. This has been happening to me for a while now in V10, but I assumed it might have been a PC issue until another reported it today.

https://user-images.githubusercontent.com/99844555/211667380-e253b318-555d-4398-9613-cc59230e8fe6.mp4

MATT 10.10 (its been happening for a while though)
Foundry 10.291
D&D 5e 2.0.3
Firefox 108.0.1 (user report is on 108.0.2)
FTC ✔️

**Comment by karpiq24** [comment]
I'm having the same issue.

**Comment by KJTailor** [comment]
+1 on this issue

**Comment by DetailsInside** [comment]
With my limited js experience I tried a little debugging on this

Issue appears to be in the action-conifg.js constructor

Specifically the tile try/catch : 
https://github.com/ironmonk88/monks-active-tiles/blob/1313cad5c1c730b1acb3a976316e4e0fb7389329/apps/action-config.js#L32-L34

It never seems to assign tileAttr correctly and always hits the catch (at least in the limited teleporter set up I was using)

At the beginning there's no issue, but after 5-10 calls to the constructor it starts taking 30secs to open the action-config window

Since the catch is triggering anyway and tileAttr ends up as an empty array, I tried commenting out line 33 and assigning tileAttr to an empty array, and now don't see this issue anymore

**Comment by ironmonk88** [comment]
Should be fixed in the latest release
