### ISSUE TITLE
[BUG] Alter, PF2

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#650]
Actor attributes in PF2 are no longer able to be Altered; tested with the following. Hurt/Heal still works strangely enough.

* `attributes.hp.value`
* `attributes.dying.value`
* 
No errors.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/872041ab-8bca-4fb9-8b6b-1b061695ccf0

Foundry 11.315
MATT 11.15
PF2 5.8.3 (I believe this is the last pre-remaster update)
FTC yes. Not shown in the video though.

**Comment by ironmonk88** [comment]
This is a change in the PF2e system.  And there's not a lot I can do to work around it.
You'll have to use `system.attributes.hp.value`.  Problem is, PF2e allows `attributes.hp.value` to get the value, but not to save the value.  And because it comes back as a "valid" value, MATT doesn't recognize that's not writable.
