### ISSUE TITLE
[BUG] Stop Token Movement Combination

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#709]
A `Stop Token Movement` with Snap to Grid enabled, followed up by some actions (Attack & Request Roll for sure, haven't tested others) results in errors, the action thread stopping, and the token disappearing until you reload.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/d3e510c5-5d1b-4594-a033-4e2c9abd705b

Foundry 11.315
MATT 11.21
PF2 5.13.3 & D&D 5e 3.0.0

**Comment by ExileofBrokenSky** [comment]
Encountering this as well, it doesn't like it if the token stops inside the tile, but if it passes through fully the action works normally.

**Comment by nozero1** [comment]
I am still running into this one. Excluding 'Stop Token Movement' seems the only option available at the moment.

**Comment by Crowguard** [comment]
This is still an issue on MATT 11.22.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/a9a9cf9b-6f6a-4ac2-8b09-4903a776cf0b

**Comment by howardad** [comment]
I am also seeing this with MATT 11.22. The cause seems to be the snap-to-grid option on Stop Token Movement followed by certain actions. Some actions are fine, others are not. Some examples of following actions that do not cause the issue are Pause Game, Send Notification, Chat Message, Ping, Pan Canvas and Change Movement Mode. Some examples of following actions that do cause the issue are Attack, Show Dialog, Show/Hide, Tile Animation, Rotation, Open Actor Sheet, and Teleport.

**Comment by Foundry37** [comment]
I've just found this on MATT 11.23. For me it's as simple as a tile that has Stop Token Movement with Snap to Grid and then Stop Remaining Tile Actions.

I managed to screenshot _just_ before the token disappeared:
![Screenshot 2024-03-25](https://github.com/ironmonk88/monks-active-tiles/assets/99896703/7fc8f1d8-8361-4be2-b60d-626c495ca2e5)

If I turn off Snap to Grid it seems to like it better, stopping me halfway into the 1x1 tile and not vanishing my character.

It seems to not like a token stopping fully inside the 1x1 tile space, you'll get the weird x & y integer warning, and then you can refresh the whole scene to make the token re-appear inside the 1x1 tile.
