### ISSUE TITLE
[BUG] Lighting Triggers Twice

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-active-tiles#723]
Tiles triggered by lighting change are running their actions twice per lighting change.

https://github.com/ironmonk88/monks-active-tiles/assets/99844555/9e289dec-7e5c-43a1-a8ae-483ceaeebf50

Also, there's a weird issue with the Chat Message in this video; I hadn't specifically set a speaker, the first chat message is from "Gamemaster" while the second one is from Player3/Amiri. Could be related?

Foundry 11.315
MATT 11.22

**Comment by ironmonk88** [comment]
You have two players logged in.  The GM and Player 3... so of course they're both going to trigger, because the light has changed for both of them.  It's similar to having both the GM and the player click on the tile at the same time.  It's going to trigger twice.
Working as expected... since you still want a light change to trigger even if the GM isn't logged in.  You just need to filter by user type in that case.
